# This is a generated file. Not intended for manual editing.
version: "3.4"
services:
  rdf.gl:
    build:
      context: "C:\\Users\\av0408\\source\\repos\\RDF.GL"
      dockerfile: "RDF.GL/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/rider-debugger/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/rider-debugger/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/rider-debugger"
      RESHARPER_LOG_CONF: "/etc/opt/rider-debugger/backend-log.xml"
    image: "rdfgl:dev"
    ports:
    - "127.0.0.1:57019:57100"
    - "127.0.0.1:57219:57300"
    volumes:
    - "C:\\Users\\av0408\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\av0408\\source\\repos\\RDF.GL\\RDF.GL:/app:rw"
    - "C:\\Users\\av0408\\source\\repos\\RDF.GL:/src:rw"
    - "C:\\Users\\av0408\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.2.7\\\
      Linux64:/opt/rider-debugger"
    - "C:\\Program Files\\JetBrains\\JetBrains Rider 2024.2.7\\bin:/etc/opt/rider-debugger/backend-log.xml"
    - "C:\\Users\\av0408\\AppData\\Local\\JetBrains\\Rider2024.2\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2024_12_23_08_53_46:/var/opt/rider-debugger:rw"
    working_dir: "/app"
